Taller.AplicacionWeb/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Taller.BLL.Interfaces;
using Taller.AplicacionWeb.Models.ViewModels;
using Taller.Entity;
using Microsoft.AspNetCore.Authorization;

namespace Taller.AplicacionWeb.Controllers
{
    public class AccesoController : Controller
    {
        private readonly IUsuarioServices _usuarioServices;

        public AccesoController(IUsuarioServices usuarioServices)
        {
            _usuarioServices = usuarioServices;
        }


        public IActionResult Login()
        {
            ClaimsPrincipal claimsUsuario = HttpContext.User;
            if (claimsUsuario.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Login(VMTblUsuario modelo)
        {
            TblUsuario usuario_encontrado = await _usuarioServices.ObtenerPorCredenciales(modelo.NombreDeUsuario, modelo.Contrasena);
            
            if (usuario_encontrado == null)
            {
                ViewData["Mensaje"] = "Usuario o contraseña incorrecta";
                return View();
            }

            ViewData["Mensaje"] = null;

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name,usuario_encontrado.NombreDeUsuario),
                new Claim(ClaimTypes.NameIdentifier,usuario_encontrado.IdUsuario.ToString()),
                new Claim(ClaimTypes.Role,usuario_encontrado.IdRol.ToString()),
                 new Claim("UrlFoto",usuario_encontrado.UrlFoto),
                 

            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = true
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

            if (usuario_encontrado.IdRol==2)
            {
                return RedirectToAction("Index", "Reparacion");
            }
            else if (usuario_encontrado.IdRol==3)
            {
                return RedirectToAction("Index", "Venta");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Taller.AplicacionWeb/Views/Acceso/Login.cshtml
@model Taller.AplicacionWeb.Models.ViewModels.VMTblUsuario

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="ES">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Taller Miguelito - Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    
    <link href="~/css/sb-admin-2.css" rel="stylesheet">

</head>

<body class="bg-gradient-info">

    <div class="container">

        
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Inicio de Sesion</h1>
                                    </div>
                                    <form class="user" asp-controller="Acceso" asp-action="Login" method="post">
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user" placeholder="Usuario" asp-for="NombreDeUsuario">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" placeholder="Contraseña" asp-for="Contrasena">
                                        </div>
                                        
                                        @if (ViewData["Mensaje"] != null)
                                        {
                                            <div class="form-group">
                                                <div class="alert alert-danger" role="alert">
                                                    @ViewData["Mensaje"]
                                                </div>
                                            </div>
                                        }



                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Ingresar
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="#">¿Olvidó su contraseña?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>


</body>

</html>